//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL
    {
        public decimal Employee_id { get; set; }
        public string Employee_Name { get; set; }
        public string Address { get; set; }
        public decimal phone_number { get; set; }
        public int Age { get; set; }
        public string Supervisor_Name { get; set; }
        public string Department { get; set; }
        public string Employee_status { get; set; }
    }
}
